### ISSUE TITLE
Join Exception messages with previous WARN line

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/LogSearchShipper#102]
Exceptions for MEPS are logged over 2 lines:
![meps_log 1](https://cloud.githubusercontent.com/assets/227505/7637121/80396c1a-fa20-11e4-9c61-997ed3e4e4db.png)

Results in:
![logsearch](https://cloud.githubusercontent.com/assets/227505/7637123/82f8bb90-fa20-11e4-8e20-25aa227f8b35.png)

We need these to be joined into a single log line

**Comment by mrdavidlaing** [comment]
Joining of log lines is handled by nxlog, specifically via [this config](https://github.com/cityindex/LogSearchShipper/blob/master/src/LogsearchShipper.Core/NxLog/NxLogProcessManager.cs#L343-L347):

```
<Extension multiline>
		Module	xm_multiline
		#HeaderLine == Anything not starting with whitespace
		HeaderLine	/^([^ ]+).*/
</Extension>
```

nxlog multiline docs [here](http://nxlog-ce.sourceforge.net/nxlog-docs/en/nxlog-reference-manual.html#xm_multiline)

Simplest case would be for the exception to be logged with some whitespace at the beginning of the `Cityindex.Atlas...FxConversionException` - that would automatically cause the Exception to be joined with the previous WARN line.

@ewilde - Is that possible?

**Comment by ewilde** [comment]
Hi Dave,

I played around with changing the layoutpattern adding a space before the exception
```xml
<layout type="log4net.Layout.PatternLayout">
     <conversionPattern value="%d %-5p %t %c - %m%n %exception"/>
 </layout>
```

Unfortunately there is no way to do that only if %exception is not null. This then effects the whole output:


![image](https://cloud.githubusercontent.com/assets/329397/7650486/dcf8ff96-faee-11e4-97e0-52d72e90b0e1.png)
Feel free to run my sample (https://github.com/ewilde/dotnet-playground/blob/451479e40f04333f052fa1d86fef00cfd444634f/logging/log4net-example/App.config#L66-L68)

Other people tackling this problem:

* Create a custom conversion item: http://stackoverflow.com/questions/15927351/how-to-add-indentation-to-multi-line-log-entry-in-log4net 
* Problem: http://stackoverflow.com/questions/28206172/q-log4net-file-parse-with-regex-nxlog 
 * Use json instead: http://sourceforge.net/projects/log4net-json/

**Comment by mrdavidlaing** [comment]
@ewilde - foo :(

@fandrei - any ideas?

What about if we made the Headerline rule "anything that starts with YYYY-MM-DD" ?

**Comment by ewilde** [comment]
@mrdavidlaing that sounds like it should work for CI log4net logs

**Comment by fandrei** [comment]
@mrdavidlaing, sounds like a feasible solution.

**Comment by fandrei** [comment]
@mrdavidlaing, where can I get more samples of such logs?

**Comment by ewilde** [comment]
@fandrei I've saved a sample log it's on the O-drive O:\Development\Technical Architecture Team Data\LogSearch\logsearch-issue-102.zip.

If you can't access that and want it somewhere else (or emailed) let me know

**Comment by fandrei** [comment]
@ewilde, could you email it to andrei.faber at labs.cityindex.com?

**Comment by fandrei** [comment]
@ewilde, thanks

**Comment by fandrei** [comment]
@mrdavidlaing, @ewilde 

one probable drawback of the headerline solution is that shipping of the last log line will be delayed until the next line is written, and the very last line will be probably lost.

**Comment by mrdavidlaing** [comment]
@fandrei - I think we can live with that.

**Comment by fandrei** [comment]
@mrdavidlaing however, there are alternative solutions.
1. programmatic pattern converter on the writing side to append space at the beginning of the first exception info line
2. use nxlog module variables, so we can remember the last line (and then append it to the exception info, when it arrives to the log)

**Comment by mrdavidlaing** [comment]
@fandrei - let's go with the simplest solution to start with; we can add complexity if necessary later down the road

**Comment by fandrei** [comment]
@mrdavidlaing, ok

**Comment by fandrei** [comment]
@mrdavidlaing, I've tried this approach, but it's producing strange results:
```
WARN  2015-05-18 22:00:00,187 Margin_3 Services.PriceService Field: 'RollFinDate' Market: '401038714' - not converting to DateTime as number of days is 0
{"@timestamp":"2015-05-19T09:38:40.592Z","Message":"Truncating D:\\projects\\CityIndex\\LogSearchShipper\\bin\\data\\nxlog.log","logger":"LogSearchShipper.Core.NxLog.NxLogProcessManager","level":"INFO"}

WARN  2015-05-18 22:00:00,203 Margin_3 Services.FxConversionService Failed to validate Live primary rate Mid=1,Bid=1,Ask=1,IsValid=False, result Primary:0, Secondary:, Side:Mid, Map:Key[From=11,To=6],Primary[Pair[From=6,To=11],Invert=True],Secondary[], Errored:True

WARN  2015-05-18 22:00:00,203 Margin_3 Application.BackToBaseConversionService Fx calculation failed for trading account id(400198853), money 106.26 USD to ccy GBP, rate type Live. Using intraDay rates instead, converted: 63.29 GBP
CityIndex.Atlas.Services.FxConversionException: failed to validate primary rate
   at CityIndex.Atlas.Services.FxConversionService.CalculateRateWithAudit(Int32 fromCurrency, Int32 toCurrency, TargetSide side, FxRateType type) in d:\Agent2\work\62d4e863a47d4e32\MTSubsystem\Price\Repository\FxConversionService.cs:line 103
   at CityIndex.Atlas.Services.FxConversionService.CalculateWithAudit(Money money, Currency toCurrency, TargetSide side, FxRateType type) in d:\Agent2\work\62d4e863a47d4e32\MTSubsystem\Price\Repository\FxConversionService.cs:line 82
   at CityIndex.Atlas.Application.BackToBaseConversionService.Calculate(Int32 tradingaccountId, Money originalAmount, Currency toCurrency, TargetSide side, FxRateType fxRateType, Decimal& rate) in d:\Agent2\work\1f7948e7a36e1bab\MTApplication\FinancialCalculations\BackToBaseConversion\BackToBaseConversionService.cs:line 159 - CcyPair From=11,To=6, Type Live, FxRate: Mid=1,Bid=1,Ask=1,IsValid=False, Result Primary:0, Secondary:, Side:Mid, Map:Key[From=11,To=6],Primary[Pair[From=6,To=11],Invert=True],Secondary[], Errored:True
{"@timestamp":"2015-05-19T09:38:46.604Z","Message":"ReportProcessorTimeUsage() started","logger":"LogSearchShipper.Core.NxLog.NxLogProcessManager","level":"INFO"}

WARN  2015-05-18 22:00:00,203 Margin_3 Services.FxConversionService Failed to validate Live primary rate Mid=1,Bid=1,Ask=1,IsValid=False, result Primary:0, Secondary:, Side:Mid, Map:Key[From=11,To=6],Primary[Pair[From=6,To=11],Invert=True],Secondary[], Errored:True
```
(from output redirected to a file)

headerline was like this:
```
		HeaderLine	/^[A-Z]+[ \t]+\d{{4}}.*/
```

I don't fully understand how this magic works, but it looks like nxlog is trying to treat *every* line that matches the headerline rule as a part of multi-line message.

**Comment by fandrei** [comment]
PS or maybe it's just adding extra linefeeds in a funny way. I'll try to analyze and compare these logs.

**Comment by fandrei** [comment]
https://github.com/cityindex/LogSearchShipper/pull/105

**Comment by mrdavidlaing** [comment]
@fandrei - my understanding is that nxlog treats any line that matches the Headerline regex as the beginning of the next log line "block".  The block continues until the next Headerline is matched.

The fact that it appears we have some logs that start with YYYY and some that start with LEVEL complicates things unfortunately.

Is it possible to apply one headerline rule to one log type, and another to another log type?

**Comment by fandrei** [comment]
@mrdavidlaing, yes. Unfortunately, all this is going to take more time than I have before the second part of my holiday, which starts tomorrow.

**Comment by fandrei** [comment]
Currently, the headerline pattern is the same for all inputs.

**Comment by fandrei** [comment]
@mrdavidlaing, I've done comparison of logs shipped with old and new headerline `/^[A-Z]+[ \t]+\d{{4}}-.*/`, and nxlog is shipping some extra empty lines when using a new headerline; however, it seems to work well enough otherwise.
Q:
1. Should I just make an option to turn on/off this new headerline, or make the headerline pattern configurable?
2. Currently the same headerline is used for all watch items within the same instance of LSS. Should I make it configurable for every watch element separately?

**Comment by mrdavidlaing** [comment]
Lets go with 2; ie, keep the existing multiline rule as the default, and allow it to be overridden.

 Eg, in our nxlog.conf if have
 ```   
    <Extension multiline_default>
            Module    xm_multiline
            #HeaderLine == Anything not starting with whitespace
            HeaderLine    /^([^ ]+).*/
    </Extension>
    <Extension multiline_ci_log4net>
            Module    xm_multiline
            #HeaderLine == Anything starting with some capital letters (e.g, ERROR, WARN) or YYYY
            HeaderLine    /^[A-Z]+[ \t]+\d{{4}}-.*/
    </Extension>
```

By default everything gets multilineRule=“multiline_default”, unless overridden like this:
```
    <watch dataFile="\\pkh-stg-web01\Logs\EDBDataSerializer\PPE\Latest.xml" >
            <field key="environment" value="PPE" />
            <overrideConfigs>
                <overrideConfig forServiceNames=“MarginProcessor.*” multilineRule="multiline_ci_log4net"/>
                </overrideConfigs>  
         </overrideConfigs>
    </watch>
```
