### ISSUE TITLE
More sensible defaults to  <edbFileWatchers><watch networkAreas, serviceNames, serverNames> to .*

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/LogSearchShipper#103]
Currently the networkAreas, serviceNames and serverNames attributes are not required, but default to not matching anything.

ie, if you want to select everything on a specific serverName, you configuration like this won't work:

```
       <edbFileWatchers>
				<watch 
					dataFile="\\pkh-stg-web01\Logs\EDBDataSerializer\PPE\Latest.xml"
					serverNames="PKH-PPE-APP57">
						<field key="environment" value="PPE" />
				</watch>
``` 

Rather, you have to write configuration like this:

```
<edbFileWatchers>
				<watch 
					dataFile="\\pkh-stg-web01\Logs\EDBDataSerializer\PPE\Latest.xml"
					networkAreas=".*"
					serviceNames=".*"
					serverNames="PKH-PPE-APP57">
						<field key="environment" value="PPE" />
				</watch>
```

I think it would be better to default networkAreas, serviceNames and serverNames attributes to `.*` (ie, match everything)

**Comment by mrdavidlaing** [comment]
@fandrei - What do you think of this idea?

**Comment by fandrei** [comment]
@mrdavidlaing, well, I'm not a user of this feature. If it's useful for someone, let's do it :)

**Comment by mrdavidlaing** [comment]
@fandrei, ok.  I'll schedule it for this release, since it should be pretty simple to implement.
