### ISSUE TITLE
edbFileWatchers -> ship local files

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/LogSearchShipper#104]
Currently the edbFileWatcher always ships files via UNC paths. 

ie, 
```xml
<edbFileWatchers>
	<watch 
		dataFile="\\pkh-stg-web01\Logs\EDBDataSerializer\PPE\Latest.xml"
		networkAreas=".*"
		serverNames="PKH-PPE-APP57"
		serviceNames="ClientPreferenceGateway"
		>
			<field key="environment" value="PPE" />
	</watch>
</edbFileWatchers>
```

Will ship:
```
File	"\\\\PKH-PPE-APP57\\Logs\\ClientPreferenceGateway\\ClientPreferenceGateway.log"
```

LogsearchShipper should ship via the local file path - i.e: `D:\Logs\ClientPreferenceGateway\ClientPreferenceGateway.log` - when this is accessible by the shipper.

**Comment by mrdavidlaing** [comment]
@fandrei - I'm not really sure what the best way to implement this is.

One idea I have is to make it transparent to the user by having [EDBFileWatchParser.AddFileWatchElementForLogFile()](https://github.com/cityindex/LogSearchShipper/blob/master/src/LogsearchShipper.Core/EDBFileWatchParser.cs#L146) do some custom logic to rewrite the `logFile` value when `D:\Logs\ClientPreferenceGateway\ClientPreferenceGateway.log` is accessible

Another idea is to add a configOverride that applies a [Regex.Replace()](https://msdn.microsoft.com/en-us/library/xwewhkd1%28v=vs.110%29.aspx))
 to the `logFile`, eg:
```
<overrideConfigs>
           <overrideConfig forServiceNames="ClientPreferenceGateway">
                <rewriteLogfile input="\\PKH-PPE-APP57" replacement="D:">
```

What do you think?

**Comment by mrdavidlaing** [comment]
@fandrei - having slept on it; I think the second `rewriteLogfile` is a better option.  It makes the config a little more complex; but it makes it clear to the operator that the `\\UNC\` -> `D:\` replacement is happening, rather than some unexepected magic happening behind the scenes.

Hopefully `rewriteLogfile` is reasonably easy to implement?

**Comment by fandrei** [comment]
@mrdavidlaing, this doesn't look difficult. However, I'd implement it using a list of UNC->local path mappings. Maybe it's even possible to populate it automagically.

**Comment by mrdavidlaing** [comment]
@fandrei - trouble is, you don't know at config time exactly which UNC paths are going to get pulled out of EDB (there might be one, there might be 10).

What you do know is that you've selected logs that only live on the machine the shipper is running on (eg `PKH-PPE-APP57`); so they are all going to start with `\\PKH-PPE-APP57\Logs`, which you also know is a shared folder mapped to `D:\Logs`

**Comment by fandrei** [comment]
@mrdavidlaing, I think it should be quite easy to list local file shares (and their local paths) in runtime and check which ones match paths from EDB file.

**Comment by mrdavidlaing** [comment]
Ok - why don't you give that approach a go and lets see how it works out

**Comment by mrdavidlaing** [comment]
Lets just make it a configuration option that you explicitly turn on; so it doesn't come as a "magic surprise" to the operator

**Comment by fandrei** [comment]
@mrdavidlaing, ok

**Comment by fandrei** [comment]
@mrdavidlaing, do I understand correctly that "watch files-" element can contain a file path or wildcard, but not a list of paths?

**Comment by mrdavidlaing** [comment]
@fandrei,

> "watch files-" element can contain a file path or wildcard, but not a list of paths?

That is correct.

**Comment by mrdavidlaing** [comment]
You can toggle this feature on and off (its off by default) using the `resolve_unc_paths` attribute of the top level `<LogSearchShipper` element:

```
<LogSearchShipper data_folder="C:\Apps\LogSearchShipper-DEV\data" 	
                                 resolve_unc_paths="True" 
...
