### ISSUE TITLE
Missing data for "logger:EdbExpectedEventSourcesLogger"

### ISSUE THREAD

**Issue by ryanholder** [cityindex/LogSearchShipper#114]
@fandrei if you look at the following selected lines it seems that we are missing the data within <Entity> for the services.

https://github.com/cityindex/LogSearchShipper/blob/master/src/LogsearchShipper.Core.Tests/SampleData/EDB/ENV1/Latest.xml#L15-L43

We also need to parse out the type of service which can be found in the following example. In this case we would need the "WindowsService"
```
<Entity xsi:type="WindowsService">
```

**Comment by fandrei** [comment]
@ryanholder, i.e. we need to read additional fields from service definitions in EDB files and ship them with every record?

**Comment by ryanholder** [comment]
@fandrei yes that is correct, the entity information for each service needs to be available.
