### ISSUE TITLE
Logpath data per service missing

### ISSUE THREAD

**Issue by ryanholder** [cityindex/LogSearchShipper#120]
@fandrei If you look at the following line of the EDBFileWatchParser file - https://github.com/cityindex/LogSearchShipper/pull/116/files#diff-6425c038385880d8bc5f6823309fc3c9R143

The logpath information is not available in a field, could we bring that in ?

**Comment by fandrei** [comment]
@ryanholder,
1. I recon you mean logs of logger:EdbExpectedEventSourcesLogger?
2. Should LogPath1, LogPath2 be included too?
3. LogPathType, LogPath1Type, LogPath2Type too?

**Comment by ryanholder** [comment]
@fandrei yes LogPath, LogPathType, LogPath1, LogPath1Type, LogPath2, LogPath2Type
