### ISSUE TITLE
Shipping of servers with no services

### ISSUE THREAD

**Issue by ryanholder** [cityindex/LogSearchShipper#126]
@fandrei, after some user testing on the Environment diagram with the new datasource it was pointed out that they would like to see the servers that have no services listed. An example of this on the current live system can be seen in the following image.
<img width="428" alt="screenshot 2015-07-24 11 07 04" src="https://cloud.githubusercontent.com/assets/352654/8872466/1fce8d44-31f5-11e5-91a3-e46ca9969d4f.png">
Initially I thought the issue was with the aggregations search I was running but upon further testing it seems as though the data is not being shipped in at all.

This is a search on the data with a server that has services - http://kibana4.cityindex.logsearch.io/#/discover?_g=(refreshInterval:(display:Off,pause:!f,section:0,value:0),time:(from:now-12h,mode:quick,to:now))&_a=(columns:!(_source),index:'logstash-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'logger:EdbExpectedEventSourcesLogger%20AND%20environment:PPE%20AND%20host:PKH-PPE-WEB35')),sort:!('@timestamp',desc))

This is a search on the data with a server that has no services - http://kibana4.cityindex.logsearch.io/#/discover?_g=(refreshInterval:(display:Off,pause:!f,section:0,value:0),time:(from:now-12h,mode:quick,to:now))&_a=(columns:!(_source),index:'logstash-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'logger:EdbExpectedEventSourcesLogger%20AND%20environment:PPE%20AND%20host:PKH-PPE-WEB42')),sort:!('@timestamp',desc))

----------

If I am correct in that we are not shipping in the data for servers with no services then I would like to propose the following;
* As per City Index users request we need that data shipped in
* Once we start shipping that data I can test to see if my current aggregations search will find the empty servers and in the event it does not we will need to include a "dummy service" which will indicate the server has no services and might be ready for decommission.

If we get the first bullet point in place we can determine action on the second bullet point.

Let me know if you have any questions ?

**Comment by fandrei** [comment]
@ryanholder, looks quite easy to do.

@mrdavidlaing, should we create a new LSS milestone for this feature, or add it to 1.10.0?

**Comment by mrdavidlaing** [comment]
@fandrei - new milestone I think

**Comment by fandrei** [comment]
@ryanholder, sample output:

```
{"@timestamp":"2015-07-28T06:07:20.006Z","environment":"ENV1","cluster":"APP","host":"ENV1-APP01","serverDescription":"The app server","logger":"EdbExpectedEventSourcesLogger","level":"INFO"}
{"@timestamp":"2015-07-28T06:07:20.008Z","environment":"ENV1","cluster":"APP","host":"ENV1-APP01","serverDescription":"The app server","service":"PriceHistoryServiceHost","serviceName":"Price History Service Host","serviceDescription":null,"event_source":"\\\\PKH-PPE-APP10\\logs\\Apps\\PriceHistoryService\\log.log","expected_state":"stopped","serviceType":"WindowsService","binaryPath":"\"D:\\Apps\\PriceHistoryServiceHost\\PriceHistoryServiceHost.exe\"","systemArea":"CORE","tags":"service_tag1,service_tag2","bundlePath":"","website":null,"applicationUri":null,"logPath":"\\\\PKH-PPE-APP10\\logs\\Apps\\PriceHistoryService\\log.log","logPathType":"log4net","logPath1":"\\\\PKH-PPE-APP10\\logs\\Apps\\PriceHistoryService\\PriceHistoryStats.log","logPath1Type":"log4net_stats","logPath2":"\\\\PKH-PPE-APP10\\","logPath2Type":"","logger":"EdbExpectedEventSourcesLogger","level":"INFO"}
{"@timestamp":"2015-07-28T06:07:20.011Z","environment":"ENV1","cluster":"APP","host":"ENV1-APP01","serverDescription":"The app server","service":"PriceHistoryServiceHost","serviceName":"Price History Service Host","serviceDescription":null,"event_source":"\\\\PKH-PPE-APP10\\logs\\Apps\\PriceHistoryService\\PriceHistoryStats.log","expected_state":"stopped","serviceType":"WindowsService","binaryPath":"\"D:\\Apps\\PriceHistoryServiceHost\\PriceHistoryServiceHost.exe\"","systemArea":"CORE","tags":"service_tag1,service_tag2","bundlePath":"","website":null,"applicationUri":null,"logPath":"\\\\PKH-PPE-APP10\\logs\\Apps\\PriceHistoryService\\log.log","logPathType":"log4net","logPath1":"\\\\PKH-PPE-APP10\\logs\\Apps\\PriceHistoryService\\PriceHistoryStats.log","logPath1Type":"log4net_stats","logPath2":"\\\\PKH-PPE-APP10\\","logPath2Type":"","logger":"EdbExpectedEventSourcesLogger","level":"INFO"}
{"@timestamp":"2015-07-28T06:07:20.012Z","environment":"ENV1","cluster":"APP","host":"ENV1-APP01","serverDescription":"The app server","service":"PriceHistoryServiceHost","serviceName":"Price History Service Host","serviceDescription":null,"event_source":"\\\\PKH-PPE-APP10\\","expected_state":"stopped","serviceType":"WindowsService","binaryPath":"\"D:\\Apps\\PriceHistoryServiceHost\\PriceHistoryServiceHost.exe\"","systemArea":"CORE","tags":"service_tag1,service_tag2","bundlePath":"","website":null,"applicationUri":null,"logPath":"\\\\PKH-PPE-APP10\\logs\\Apps\\PriceHistoryService\\log.log","logPathType":"log4net","logPath1":"\\\\PKH-PPE-APP10\\logs\\Apps\\PriceHistoryService\\PriceHistoryStats.log","logPath1Type":"log4net_stats","logPath2":"\\\\PKH-PPE-APP10\\","logPath2Type":"","logger":"EdbExpectedEventSourcesLogger","level":"INFO"}
```
How does it look?

**Comment by ryanholder** [comment]
@fandrei that look good thanks, I do have one question;

* How easy would it be to add a ```service, serviceName, serviceDescription``` filled with values of ```None, None, No services to display```

I don't want to complicate the shipper code but am still uncertain if my Aggs search will work if there is no services for a particular host. Thoughts ?

**Comment by fandrei** [comment]
@ryanholder, that's easy. sample:
```
{"@timestamp":"2015-07-28T08:08:24.502Z","environment":"ENV1","cluster":"APP","host":"ENV1-APP01","serverDescription":"The app server","service":"None","serviceName":"None","serviceDescription":"No services to display","logger":"EdbExpectedEventSourcesLogger","level":"INFO"}
```

**Comment by ryanholder** [comment]
@fandrei, thanks!!

**Comment by fandrei** [comment]
https://github.com/cityindex/LogSearchShipper/pull/128

**Comment by fandrei** [comment]
@ryanholder, you're welcome.
We can deploy it as soon as @mrdavidlaing approves

**Comment by mrdavidlaing** [comment]
@fandrei - merge away

**Comment by fandrei** [comment]
@mrdavidlaing, done
