### ISSUE TITLE
Only restart nxlog when EDB config affecting that instance changes

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/LogSearchShipper#127]
Currently, when configuring LSS via an EDB XML file:
```
<watch dataFile="SampleData\EDB\ENV1\Latest.xml" logEnvironmentDiagramDataEveryMinutes="10"
					networkAreas=".*" serverNames=".*" serviceNames="Price|Margin">
					<field key="environment" value="QAT" />
					<!-- Override watching settings for matched services -->
					<overrideConfigs>
						<overrideConfig forServiceNames="Price" closeWhenIdle="false">
							<customNxLogConfig>
								Exec   if not ($raw_event =~ /DEBUG/ ) drop();
							</customNxLogConfig>
						</overrideConfig>
					</overrideConfigs>
				</watch>
```
Every change to `Latest.xml` will cause LSS to restart the `nxlog` shipping service. ( [see](https://github.com/cityindex/LogSearchShipper/blob/master/src/LogsearchShipper.Core/ConfigWatcher.cs) )

This should be refined so that the `nxlog` shipping service is only restarted when the changes relate to the files configured to be shipped.

ie, in the above example, the `nxlog` shipping service should only be restarted when the change to `SampleData\EDB\ENV1\Latest.xml` is related to `serviceNames="Price|Margin"`

**Comment by fandrei** [comment]
@mrdavidlaing, sounds like this will require quite convoluted logic. Why don't make LSS restart nxlog only when nxlog config is changed, instead?

**Comment by mrdavidlaing** [comment]
> Why don't make LSS restart the nxlog service only when nxlog content config has been changed, instead?

@fandrei - that sounds like a very elegant solution.  Since `NxlogProcessManager` exposes a [`Config` property](https://github.com/cityindex/LogSearchShipper/blob/master/src/LogsearchShipper.Core/NxLog/NxLogProcessManager.cs#L28), you could do something like:

(psuedocode)
```
...on watched EDB config file change...
var oldConfig = nxLogProcessManager.Config;
GenerateNxLogConfig();
if nxLogProcessManager.Config != oldConfig {
   RestartNxLog();
}
```
