### ISSUE TITLE
Add serviceType to our "dummy" service in empty servers

### ISSUE THREAD

**Issue by ryanholder** [cityindex/LogSearchShipper#129]
@fandrei in the changes you made against issue #126 

We added dummy data for ```service, serviceName, serviceDescription```

Could we include ```serviceType``` in to this and the value for the field should be "NoService"

When making changes to the diagram I realised there is some logic that requires this. @mrdavidlaing said it might be possible to add this to the release you are going to deploy this week ?

**Comment by fandrei** [comment]
@ryanholder, why not
