### ISSUE TITLE
Ship custom windows event log entries

### ISSUE THREAD

**Issue by ewilde** [cityindex/LogSearchShipper#135]
# Summary
Ability to ship specific list of windows event logs

# Description
A users defines a custom list of events they want to ship using the windows event viewer:

![image](https://cloud.githubusercontent.com/assets/329397/9465384/087fe1cc-4b24-11e5-946a-0b366a90ef55.png)

![image](https://cloud.githubusercontent.com/assets/329397/9465398/35fb951a-4b24-11e5-9acd-7fea6b9f538e.png)

Saving this custom view will generate an xml file containing the filter query:

```xml
<QueryNode>
	<Name>ASP.NET</Name>
	<QueryList>
		<Query Id="0" Path="Application">
			<Select Path="Application">*[System[Provider[@Name='.NET Runtime' or @Name='ASP.NET 4.0.30319.0'] and (Level=1  or Level=2 or Level=3 or Level=4 or Level=0 or Level=5)]]</Select>
		</Query>
	</QueryList>
</QueryNode>
```

Can we use this query to configure nslog to ship event logs that pass this filter?

A cursory google suggests we can:

http://serverfault.com/questions/543494/query-specific-logs-from-event-log-using-nxlog

**Comment by fandrei** [comment]
https://github.com/cityindex/LogSearchShipper/pull/138
