### ISSUE TITLE
Logsearch-shipper EnvironmentDiagram data

### ISSUE THREAD

**Issue by wilsoncg** [cityindex/LogSearchShipper#141]
Logsearch-shipper environmentdiagram data shipping has stopped since 2015-08-28T16:39, is this correct?

[Dashboard](http://kibana.cityindex.logsearch.io/#/dashboard/elasticsearch/logsearch-windows-shipper-environmentdiagram)

**Comment by ewilde** [comment]
@ryanholder can you comment on this issue?

**Comment by ryanholder** [comment]
@ewilde David's old office PC use to ship in the data for the environment diagram but we now make use of the shippers that Andrei put in place.

Looking at filter query it seems it is searching against a field that no longer exists and the time mentioned by @wilsoncg is when we made the switch and probably when the shipper from David's PC would have been switched off.

@wilsoncg what was the purpose of this Dashboard, if still required can you change the filter query to use the fields available ? If the dashboard is not required then I would delete it.

**Comment by mikelear** [comment]
Hello :)
