### ISSUE TITLE
Delete logs older than 2 days

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/LogSearchShipper#63]
Old "rolled" LogSearchShipper log files (`LogSearchShipper.log`, `LogSearchShipperDebug.log` etc) defined in the `LogSearchShipper.exe.config` `RollingFileAppender` log4net sections don't every seem to be deleted, resulting in full disks on the machines running the LogSearchShippers:

![image](https://cloud.githubusercontent.com/assets/227505/5526081/9b2b7b70-89e7-11e4-96aa-b3d203e22137.png)

Log4Net should be configured to delete all log files older than 2 days.

Given our [current sample config](https://github.com/cityindex/LogSearchShipper/blob/master/src/LogSearchShipper/LogSearchShipper.exe.config.SAMPLE#L61-L69):
```
<appender name="RollingFileAppenderDebug" type="log4net.Appender.RollingFileAppender">
			<file value="LogSearchShipperDebug.log" />
			<appendToFile value="true" />
			<maximumFileSize value="250MB" />
			<maxSizeRollBackups value="2" />
			<layout type="log4net.Layout.PatternLayout">
				<conversionPattern value="%utcdate{ISO8601} [%thread] %-5level %logger - %.255message%newline" />
			</layout>
		</appender>
```
how can we do this?

**Comment by fandrei** [comment]
closed via #65
