### ISSUE TITLE
Evaluate switching build scripts to https://github.com/ewilde/crane  

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/LogSearchShipper#64]
https://github.com/ewilde/crane is a build automation tool being created by City Index's Ed Wilde (who manages City Index's internal build infrastructure

I'd like to see whether we can replace our custom build scripts - [`build.xml.proj`](https://github.com/cityindex/LogSearchShipper/blob/master/build.xml.proj) with this project

**Comment by fandrei** [comment]
I don't think it's useful to remake build scripts of our existing using crane. However, we can try to use it for new projects.

**Comment by mrdavidlaing** [comment]
Ok
