### ISSUE TITLE
Make nxlog.exe "failed to open..." messages easy to filter out

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/LogSearchShipper#69]
Currently nxlog.exe "error" logs get logged by the LogSearchShipper process (see [src/LogsearchShipper.Core/NxLog/NxLogOutputParser.cs](https://github.com/cityindex/LogSearchShipper/blob/master/src/LogsearchShipper.Core/NxLog/NxLogOutputParser.cs) ) as:

```
{"@timestamp":"2015-01-16T16:48:56.265Z","Message":"failed to open \\\\INX-SRV-APPL09\\Logs\\tibco\\*.log; The filename, directory name, or volume label syntax is incorrect.","logger":"nxlog.exe","level":"ERROR"}
{"@timestamp":"2015-01-16T16:48:56.266Z","Message":"input file does not exist: \\\\INX-SRV-APPL46\\Logs\\Apps\\STP\\stp.log","logger":"nxlog.exe","level":"WARN"}
{"@timestamp":"2015-01-16T16:49:06.731Z","Message":"apr_stat failed on file \\\\INX-SRV-TIB03\\Logs\\tibco\\*.log; The filename, directory name, or volume label syntax is incorrect.","logger":"nxlog.exe","level":"ERROR"}
```

We need a way to easily filter these out when looking for other logs.

**Comment by mrdavidlaing** [comment]
I propose that all these logs are set to level `WARN`, and if possible, get a new key=>value pair `"Category":"MISSING_FILE"` (or some additional field that you can filter on)

**Comment by fandrei** [comment]
@mrdavidlaing, as far as I understand these messages are produced by nxlog. Should I match all messages with these values and switch them to "Warning" level?

**Comment by mrdavidlaing** [comment]
Yes - the [src/LogsearchShipper.Core/NxLog/NxLogOutputParser.cs](https://github.com/cityindex/LogSearchShipper/blob/master/src/LogsearchShipper.Core/NxLog/NxLogOutputParser.cs class is responsible for translating the nxlog.exe log messages into Log4Net text.  

Currently it just passes the values through with basically no modification; but I think that it should be extended so that the `failed to open...`, `input file does not exist...` and `apr_stat failed on file...` messages get set to level `WARN` and, (if possible), get an additional `"Category":"MISSING_FILE"` field.

**Comment by fandrei** [comment]
@mrdavidlaing, not sure how to inject this "Category":"MISSING_FILE" field. It seems to be impossible without some refactoring.

**Comment by fandrei** [comment]
It seems I've found a way... does this formatting look ok?

```
2015-01-21 03:58:19,010 [12] WARN  nxlog.exe - { Message = failed to open directory: \\\\PKH-PPE-WEB24\\Logs\\IIS\\W3SVC1\: The specified path is invalid., Category = MISSING_FILE }
2015-01-21 03:58:19,010 [10] INFO  Topshelf.Hosts.ConsoleRunHost - The LogSearchShipper service is now running, press Control+C to exit.
2015-01-21 03:58:19,011 [12] INFO  nxlog.exe - { Message = nxlog-ce-2.8.1248 started }
2015-01-21 03:58:19,012 [12] WARN  nxlog.exe - { Message = Module in_file0 has no input files to read }
2015-01-21 03:58:19,012 [12] INFO  nxlog.exe - { Message = input file LogSearchShipper.log was truncated, restarting from beginning }
2015-01-21 03:58:20,365 [12] INFO  nxlog.exe - { Message = successfully connected to ingestor.meta.logsearch.io:443 }
```

```
{"@timestamp":"2015-01-21T03:58:19.010Z","Message":"failed to open directory: \\\\\\\\PKH-PPE-WEB24\\\\Logs\\\\IIS\\\\W3SVC1\\: The specified path is invalid.","Category":"MISSING_FILE","logger":"nxlog.exe","level":"WARN"}
{"@timestamp":"2015-01-21T03:58:19.010Z","Message":"The LogSearchShipper service is now running, press Control+C to exit.","logger":"Topshelf.Hosts.ConsoleRunHost","level":"INFO"}
{"@timestamp":"2015-01-21T03:58:19.011Z","Message":"nxlog-ce-2.8.1248 started","logger":"nxlog.exe","level":"INFO"}
{"@timestamp":"2015-01-21T03:58:19.012Z","Message":"Module in_file0 has no input files to read","logger":"nxlog.exe","level":"WARN"}
{"@timestamp":"2015-01-21T03:58:19.012Z","Message":"input file LogSearchShipper.log was truncated, restarting from beginning","logger":"nxlog.exe","level":"INFO"}
{"@timestamp":"2015-01-21T03:58:20.365Z","Message":"successfully connected to ingestor.meta.logsearch.io:443","logger":"nxlog.exe","level":"INFO"}
```

**Comment by mrdavidlaing** [comment]
That formatting looks good to me.  Lets get it deployed and see if it helps.  Where is the code?

**Comment by fandrei** [comment]
@mrdavidlaing, here it is https://github.com/cityindex/LogSearchShipper/pull/71
