### ISSUE TITLE
Don't attempt to add nxlog.log data to LogSearchShipper log

### ISSUE THREAD

**Issue by fandrei** [cityindex/LogSearchShipper#72]
It's better to make nxlog itself ship its status logs.

**Comment by fandrei** [comment]
@mrdavidlaing, what if we make nxlog to ship its status logs directly, but keep nxlog log monitoring to forward nxlog messages to the console? In this case LogSearchShipper will print nxlog messages in the console as it currently does, but possible problems with nxlog logs monitoring won't affect shipping.

**Comment by mrdavidlaing** [comment]
What would the use case of having nxlog messages routed to the console?  Since running in console mode almost never happens, I feel like it would be keeping a lot of complexity in the code for a very small benefit.

Unless I'm missing something?

**Comment by fandrei** [comment]
@mrdavidlaing, I believe debugging is the only possible use. Fine by me, if we just delete it.

**Comment by mrdavidlaing** [comment]
@fandrei - lets delete it then
