### ISSUE TITLE
Enable injecting custom nxlog config for watched file

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/LogSearchShipper#73]
This is to enable selective shipping of `MarginEventProcessorService.log` files

Adding a `<customNxLogConfig>` tag to a `fileWatchers/watch` element should inject that config into the corresponding `nxlog.conf` `<im_file>` tag.

Eg:
```xml
<fileWatchers>
	<watch files="\\inx-srv-appl50\Logs\Apps\MarginEventProcessorService\Log*.log" type="ci_log4net">
		<field key="environment" value="LIVE" />
		<field key="host" value="INX-SRV-APPL50" />
		<field key="service" value="MarginEventProcessorService" />
		<customNxLogConfig>
    	 Exec 	if not ($raw_event =~ /MarginCalculationHandler/ ) drop();
		</customNxLogConfig>
	</watch>
 </fileWatchers>
```

Should produce `nxlog.conf` like:

```
<Input in_file1>
	Module	im_file
	InputType	multiline
	File	"\\\\inx-srv-appl50\\Logs\\Apps\\MarginEventProcessorService\\Log*.log"
	ReadFromLast TRUE
	SavePos	TRUE
	CloseWhenIdle TRUE
	PollInterval 5
	DirCheckInterval 10
	Exec 	if not ($raw_event =~ /MarginCalculationHandler/ ) drop();
	Exec	$path = "\\inx-srv-appl50\Logs\Apps\MarginEventProcessorService\Log*.log"; $type = "ci_log4net"; $environment = "LIVE"; $host = "INX-SRV-APPL50"; $service = "MarginEventProcessorService"; $Message = substr($raw_event, 0, 1040000);
</Input>
```

**Comment by fandrei** [comment]
@mrdavidlaing, I haven't found any easy way to store config property as an element body, so I've used an attribute instead (to start with). 
So, config looks like this:

```
				<watch files="\\inx-srv-appl50\Logs\Apps\MarginEventProcessorService\Log*.log" type="ci_log4net"
							 customNxLogConfig="Exec   if not ($raw_event =~ /MarginCalculationHandler/ ) drop();">
					<field key="environment" value="LIVE" />
					<field key="host" value="INX-SRV-APPL50" />
					<field key="service" value="MarginEventProcessorService" />
				</watch>
```

I'll try to find a better way to solve this.

**Comment by mrdavidlaing** [comment]
@fandrei,

Sorry, just saw this. An attribute is a good start, but I don't think it will work long term.  Specifically:

1.  It will make config with quotes a pain to write.
2.  It will make multiline config's difficult to write.

**Comment by mrdavidlaing** [comment]
@fandrei - Looks like you need to do a bit of overriding to get the text out of a config element.  Fortunately, it looks fairly simple.

http://stackoverflow.com/questions/5078758/can-i-add-a-textnode-instead-of-an-attribute-in-a-net-configurationsection
