### ISSUE TITLE
LogSearchShipper restarts nxlog multiple times when EDB configs change

### ISSUE THREAD

**Issue by fandrei** [cityindex/LogSearchShipper#76]

**Comment by fandrei** [comment]
It must be caused by this http://stackoverflow.com/questions/1764809/filesystemwatcher-changed-event-is-raised-twice

**Comment by fandrei** [comment]
@mrdavidlaing, It must be caused by this file watcher's beavior http://stackoverflow.com/questions/1764809/filesystemwatcher-changed-event-is-raised-twice

**Comment by mrdavidlaing** [comment]
@fandrei - this looks like a solution that would match our use-case - http://stackoverflow.com/a/3042963

**Comment by fandrei** [comment]
@mrdavidlaing, yep. I'm trying different approaches at the moment.
