### ISSUE TITLE
Add negative filtering for networkAreas/serverNames/serviceNames

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/LogSearchShipper#81]
We need a way to do negative filtering of which EDB services are shipped.

The `edbFileWatchers/watch` element should have 3 new `NotEquals` attributes, which are combined with the matching attributes to exclude items from the matched lists.

In the following example:

```
<edbFileWatchers>
                <watch
                    dataFile="SampleData/EDB/ENV1/Latest.xml"
                    logEnvironmentDiagramDataEveryMinutes="1"
                    networkAreas="DMZ|APP"
                    networkAreasNotEquals="APP"
                    serverNames="(.*01|.*02)"
                    serverNamesNotEquals="(.*TIB|.*MOR)"
                    serviceNames="Ektron.*"
                    serviceNamesNotEquals="Ektron05.*"
            >
```

0.  Network areas `DMZ` would be shipped
0.  Server names `APP01` and `APP02` would be shipped, but not `TIB01` or `MOR02`
0.  Service names `Ektron01, Ektron02, Ektron03, Ektron04, Ektron06` would be shipped, but not `Ektron05`

**Comment by fandrei** [comment]
@mrdavidlaing, it seems "NotEquals" suffix isn't precise as we are going to use patterns there. Isn't it better to use "NotMatch" instead?

**Comment by fandrei** [comment]
PS or we can use names like "networkAreasNegative"

**Comment by mrdavidlaing** [comment]
@fandrei - `NotMatch` sounds good to me
