### ISSUE TITLE
Add CloseWhenIdle config option (defaulted to TRUE)

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/LogSearchShipper#82]
We need a new `closeWhenIdle` setting that controls the [`im_file`'s CloseWhenIdle setting](https://github.com/cityindex/LogSearchShipper/blob/master/src/LogsearchShipper.Core/NxLog/NxLogProcessManager.cs#L604).

It should default to `TRUE`, but be possible to configure as FALSE like this:

```
<watch files="C:\Windows\WindowsUpdate.log" type="plain">
        <closeWhenIdle>FALSE</closeWhenIdle>
	<field key="environment" value="ENV1" />
	<field key="service" value="WindowsUpdate" />
</watch>
```

**Comment by mrdavidlaing** [comment]
@fandrei, After some internal discussions, I think its better if we leave the default as TRUE rather than FALSE.

Its better to ship duplicates than risk locking in nearly all cases.

**Comment by fandrei** [comment]
@mrdavidlaing, why don't make it an attribute instead of sub-element?

**Comment by mrdavidlaing** [comment]
> attribute instead of sub-element
Fine by me
