### ISSUE TITLE
Add configOverride config for edbFileWatchers/watch

### ISSUE THREAD

**Issue by mrdavidlaing** [cityindex/LogSearchShipper#83]
It should be possible to "override" the configuration for a specific watch generated by the edbFileWatchers as follows:

```
<edbFileWatchers>
                <watch
                    dataFile="SampleData/EDB/ENV1/Latest.xml">
                    <field key="environment" value="ENV1" />
                    <configOverride forServiceNames=“MarginEventProcessor|Pricing”>
                        <closeWhenIdle>TRUE</closeWhenIdle>
                        <customNxLogConfig>
                            Exec   if not ($raw_event =~ /DEBUG/ ) drop();
                        </customNxLogConfig>
                    </configOverride>
                </watch>
```

In this example, the custom `closeWhenIdle` and `customNxLogConfig` config should only be applied to services with names matching `MarginEventProcessor` or `Pricing`

**Comment by fandrei** [comment]
@mrdavidlaing, should this configOverride be a single element, or multiple elements are possible?

**Comment by mrdavidlaing** [comment]
Thinking about it, supporting multiple configOverride will be necessary.

**Comment by fandrei** [comment]
@mrdavidlaing, it seems this feature is quite complicated and it's impossible to finish it today.

**Comment by fandrei** [comment]
@mrdavidlaing, does this config structure look ok?

```
						<edbFileWatchers>
							<watch dataFile="\\pkh-stg-web01\Logs\EDBDataSerializer\QAT\Latest.xml" logEnvironmentDiagramDataEveryMinutes="10"
								  networkAreas=".*" serverNames=".*" serviceNames=".*">
								<field key="environment" value="QAT" />
                <overrideConfigs>
                  <overrideConfig forServiceNames="MarginEventProcessor|Pricing" closeWhenIdle="true">
                    <customNxLogConfig>
                      Exec   if not ($raw_event =~ /DEBUG/ ) drop();
                    </customNxLogConfig>
                   </overrideConfig>
                </overrideConfigs>
							</watch>
						</edbFileWatchers>
```

**Comment by fandrei** [comment]
(it seems .NET doesn't accept "configOverride" name as "config" is a reserved prefix.)

**Comment by mrdavidlaing** [comment]
`overrideConfigs` with sub `overrideConfig` is fine.  

Who knew that you couldn't prefix with `config`!

No problem if you can't finish today; we'll just continue next week

**Comment by fandrei** [comment]
for the record - error message is " A configuration item alias for 'add' cannot have the name 'configOverride' because it starts with the reserved prefix 'config' or 'lock'."
