### ISSUE TITLE
Create a custom nxlog tailer for MT logs

### ISSUE THREAD

**Issue by fandrei** [cityindex/LogSearchShipper#89]
(it should handle zero-padded log endings)

**Comment by fandrei** [comment]
@mrdavidlaing, I've created a simple test app and it seems to be working well with im_exec module. At least at the first sight.

**Comment by mrdavidlaing** [comment]
@fandrei - let me know when you have committed some code, and I'll try it out.

**Comment by fandrei** [comment]
@mrdavidlaing, should I make it a part of this project?

**Comment by fandrei** [comment]
@mrdavidlaing, unfortunately these log files contain non-ASCII chars (and this encoding certainly is not UTF-8), and here we have some encoding translation "fun".

**Comment by fandrei** [comment]
PS I could write these data to a file keeping these non-ASCII chars intact, but writing them to the console requires to know the correct code page. And I have no idea what language it might be.

**Comment by mrdavidlaing** [comment]
@fandrei 

> should I make it a part of this project

Yes - I think you should add the tailer as a new Console project to the solution, so that the `.exe` and any related binaries end up in the same `bin` folder

**Comment by mrdavidlaing** [comment]
> writing them to the console requires to know the correct code page

Is it possible to write the test to the console such that most of it is readable, and we just get the occasional "broken" character?  

If so, then I say that is the place to start

**Comment by fandrei** [comment]
@mrdavidlaing, yes, it's possible. But it will be more like "some lines are broken".

**Comment by fandrei** [comment]
@mrdavidlaing, https://github.com/cityindex/LogSearchShipper/tree/mt_log_tailer
A very simplistic implementation here. You can try it by pointing to a MT log and redirecting output to a file (and then comparing with the original log file), or wait until I integrate it with the main application.

**Comment by mrdavidlaing** [comment]
@fandrei - Great - let me try it out now.

How do I "point it at a MT log file"?

```
MtLogTailer.exe \\server\path\tt\mt4\metatrader.log`
```

?

**Comment by fandrei** [comment]
yes. pass path of the log file as a command line argument.

**Comment by fandrei** [comment]
@mrdavidlaing, yes. pass path of the log file as a command line argument.

**Comment by mrdavidlaing** [comment]
@fandrei - hmm - is it possible to change how the log file is opened so we don't get this? :
```
PS C:\dev\logsearch-shipper.NET\bin> .\MtLogTailer.exe \\INX-SRV-MTLIV01\Apps2\MetaTrader4Server\logs\20150326.log
System.IO.IOException: The process cannot access the file '\\INX-SRV-MTLIV01\Apps2\MetaTrader4Server\logs\20150326.log'
because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShar
e share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolea
n useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at MtLogTailer.LogShipper.Process() in c:\Dev\logsearch-shipper.NET\src\MtLogTailer\LogShipper.cs:line 24
   at MtLogTailer.Program.Main(String[] args) in c:\Dev\logsearch-shipper.NET\src\MtLogTailer\Program.cs:line 27
```

**Comment by fandrei** [comment]
@mrdavidlaing, yes. Try the last update.

**Comment by mrdavidlaing** [comment]
@fandrei - awesome - that seems to work great!  

Here is a diff between what was in the source log, and what MtLogTailer.exe "shipped" - https://www.diffchecker.com/fl7pkvvp

Almost identical, except for the Chinese characters in the middle (as expected)

One small request before we move to integrating into nxlog - could you start shipping from the end of the file; since the live MT4 logs are several 100 MBs.

**Comment by fandrei** [comment]
@mrdavidlaing, ok
I also can make it process those chars correctly, if we know what encoding is that.

**Comment by mrdavidlaing** [comment]
Firefox says the encoding is `Western`.
Notepad++ says the encoding is `Dos\Windows` and `ANSI`

I'm guessing this means Windows-1252 - could you try that please.

**Comment by fandrei** [comment]
@mrdavidlaing, nope. 1252 is for Latin alphabet based languages only.

**Comment by mrdavidlaing** [comment]
Where in the code do you change what encoding is being used?

I'll cycle through the suggestions here: http://stackoverflow.com/questions/16083916/the-encoding-that-notepad-just-calls-ansi-does-anyone-know-what-to-call-it and see if any work

**Comment by fandrei** [comment]
@mrdavidlaing, I've added support for this here https://github.com/cityindex/LogSearchShipper/blob/mt_log_tailer/src/MtLogTailer/LogShipper.cs#L32

**Comment by mrdavidlaing** [comment]
@fandrei - cool - let me try a few with different encodings

**Comment by fandrei** [comment]
@mrdavidlaing, shipping from the end of file - done. Plz try it.

**Comment by mrdavidlaing** [comment]
So... codepage=936 -> gb2312 ANSI/OEM Simplified Chinese (PRC, Singapore); Chinese Simplified (GB2312) works when shipping from LON-WS01186, and NOT when shipping from INX-SRV-APP79.

I have a horrible suspicion the codepage depends on the machine doing the shipping...

**Comment by mrdavidlaing** [comment]
@fandrei - good news - shipping from end of file seems to work.

Next step - integrating this into Logsearchshipper so it can be called from nxlog's im_exec

**Comment by mrdavidlaing** [comment]
@fandrei - PS - I added https://github.com/cityindex/LogSearchShipper/commit/6cd0ab07ef74fa7f987362a6d215642f7a906af0

**Comment by fandrei** [comment]
@mrdavidlaing,
I could add encoding as an optional argument to mitigate this.

wrt integration - should I add a "log type" property to the fileWatcher element, so choosing MT type makes LSS launch this tailer?

**Comment by mrdavidlaing** [comment]
I think a property on the fileWatcher element is a good idea.

However, lets  call it `useCustomMtTailer`, since `log type` might get confused with the `@type` key we associate with logs in Logsearch to enable parsing.

**Comment by fandrei** [comment]
@mrdavidlaing, why don't call it sourceType, then?
useCustomMtTailer sounds too ad-hoc to me.

**Comment by mrdavidlaing** [comment]
I'm still against something with `Type` in the name, since I think that will be confused.   `sourceTailer` perhaps?

**Comment by fandrei** [comment]
@mrdavidlaing, ok

**Comment by 2knarf** [comment]
Are there any news on this?
