### ISSUE TITLE
MT tailer - incorrect time parsing

### ISSUE THREAD

**Issue by fandrei** [cityindex/LogSearchShipper#96]
mrdavidlaing on Tue at 19:58
The biggest issue is that we’re parsing the date incorrectly - so a log shipped NOW gets a @timestamp of NOW+1 hour

**Comment by fandrei** [comment]
@mrdavidlaing, it seems this error is on the server side

**Comment by mrdavidlaing** [comment]
My money is on these filters - https://github.com/cityindex/logsearch-for-cityindex/blob/master/src/logstash-filters/snippets/mt4proxy.conf#L14-L30

**Comment by fandrei** [comment]
closed in favor of https://github.com/cityindex/logsearch-for-cityindex/issues/65
